#!/bin/bash

green=$(tput setaf 2)
red=$(tput setaf 1)
normal=$(tput sgr0)
printer="echo"
format=""
sep="-----------------------------------------------------------------"

old_IFS=$IFS	# sauvegarde du séparateur de champ  
IFS=$'\n'		# nouveau séparateur de champ, le caractère fin de ligne  

while read line; do
	if [[ "$line" == *PASS* ]]; then
		$printer $format "${green}$sep";
		$printer $format "$line";
		$printer $format "$sep${normal}";
	elif [[ "$line" == *FAIL* ]]; then
		$printer $format "${red}$sep";
		$printer $format "$line";
		$printer $format "$sep${normal}";
	else
		$printer $format $line;
	fi
done </dev/stdin

IFS=$old_IFS	# rétablissement du séparateur de champ par défaut