#ifndef TYPEITEM_H
#define TYPEITEM_H

#define DATAITEMTYPE 100

#define TYPETRACK 1
#define TYPECURSOR 2
#define TYPECLIP 3
#define TYPETRANSITION 4
#define TYPEFILTER 5
#define TYPERULER 6
#define TYPERULERDOCK 7
#define TYPESELECTWINDOW 8

#define ZCLIP 1
#define ZCLIPSELECTED 10
#define ZCLIPCURRENT 20
#define ZTRANSITION 30
#define ZFILTER 40
#define ZSELECTWINDOW 45
#define ZRULER 50
#define ZCURSOR 60

#define RULERWIDTH 400.0
#define RULERDOCKHEIGHT 18.0
#define RULERHEIGHT 18.0
#define TRACKVIEWITEMHEIGHT 42
#define SNAPWIDTH 12



#endif // TYPEITEM_H
