#ifndef TYPEITEM_H
#define TYPEITEM_H

#define DATAITEMTYPE 100

#define TYPETRACK 1
#define TYPECURSOR 2
#define TYPECLIP 3
#define TYPETRANSITION 4
#define TYPEFILTER 5
#define TYPERULER 6

#define ZCLIP 1
#define ZCLIPSELECTED 2
#define ZTRANSITION 3
#define ZFILTER 4
#define ZRULER 9
#define ZCURSOR 10

#define TRACKVIEWITEMHEIGHT 42
#define SNAPWIDTH 8



#endif // TYPEITEM_H
